service: basic-serverless-AWS-Lambda-discord-bot

provider:
  name: aws
  runtime: python3.11
  stage: dev
  region: eu-central-1

plugins:
  - serverless-python-requirements

package:
  individually: true

functions:
  discord-bot-runner:
    name: bot-runner
    handler: main_wizard_bot
    description: wizard GPTeous discord bot runner
    timeout: 30 # seconds
    memorySize: 512 # mb
    package:
      patterns:
        - "!node_modules/**"
        - "!yarn.lock"
        - "!package-lock.json"
        - "!package.json"