name: push-aws-bot-server

# Trigger deployment only on push to production-AWS branch
on:
  push:
    branches:
      - production-AWS

jobs:
  deploy:
    name: Deploy to EC2 on every production-AWS branch push
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.11 # with a build matrix, you can specify a list of python versions to deploy with
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install python project dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Deploy to AWS EC2 discord bot server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo apt-get -y update
            sudo apt-get -y install python3
            sudo apt-get -y install python3-pip
            pkill python3
            cd src
            python3 main_wizard_bot.py
      - name:  exit on success
        run: |
          exit success
